[package]
name = "rizz_club"
version = "1.0.1"
authors = ["sonhavietnamese"]

[addresses]
rizz_club = "077b214ea7fcfec14a0df2e6d9015fa8ea8e93813ec94c93e53f9f77642b2db8"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
